// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwyOtEZ__TbdHUFyTGsCoFTPgUyJKMres',
    appId: '1:292021353252:web:b5855cd0e4f66c4f0a11b1',
    messagingSenderId: '292021353252',
    projectId: 'fir-flutter-5dfcb',
    authDomain: 'fir-flutter-5dfcb.firebaseapp.com',
    storageBucket: 'fir-flutter-5dfcb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi-htKmtgai_U0aZSOL0znyDXoXS_6ZtI',
    appId: '1:292021353252:android:af51062d8b5f20fb0a11b1',
    messagingSenderId: '292021353252',
    projectId: 'fir-flutter-5dfcb',
    storageBucket: 'fir-flutter-5dfcb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6cFTrX4XmqmAnQWT6xrJDzJRqnVjWeGA',
    appId: '1:292021353252:ios:8c8b5b20646a33010a11b1',
    messagingSenderId: '292021353252',
    projectId: 'fir-flutter-5dfcb',
    storageBucket: 'fir-flutter-5dfcb.appspot.com',
    iosBundleId: 'com.example.userAuthenticaton',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6cFTrX4XmqmAnQWT6xrJDzJRqnVjWeGA',
    appId: '1:292021353252:ios:8c8b5b20646a33010a11b1',
    messagingSenderId: '292021353252',
    projectId: 'fir-flutter-5dfcb',
    storageBucket: 'fir-flutter-5dfcb.appspot.com',
    iosBundleId: 'com.example.userAuthenticaton',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwyOtEZ__TbdHUFyTGsCoFTPgUyJKMres',
    appId: '1:292021353252:web:81abb9313c5211380a11b1',
    messagingSenderId: '292021353252',
    projectId: 'fir-flutter-5dfcb',
    authDomain: 'fir-flutter-5dfcb.firebaseapp.com',
    storageBucket: 'fir-flutter-5dfcb.appspot.com',
  );
}
